### PR TITLE
GLES 2.0 and basic 3D support

### PR DESCRIPTION
**Pull request by hgy29**
These changes introduce basic 3D support in meshes and frustum setting.
This worked imposed some heavy changes in core Gideros graphics:
- Switch to OpenGL ES 2.0 programmable pipeline instead of OpenGL 1.1 fixed pipeline. Right now shaders are set up to mimic fixed pipeline behavior as used by gideros
- Implements 3D matrix transforms (i.e. 4x4 matrices), and add related API calls in Sprite class
- Add frustum setting API in Application class to enable perspective projection
- Add depth buffer setting and checking, and setup stencil buffers for future masking (or shading) option.
- Add a 3D parameter on mesh objetcs, merely specifying if vertex take two or three coordinates

Note: I've currently tested the changes againts Windows gideros player, two different android devices, an iPhone 6. I am fairly confident that everything should work smoothly on all iOS devices starting from iPhone 3GS (won't work for earlier phones), and they should work on most recent android devices (theoretically starting from Froyo). I couldn't compile gideros player for macos yet, but since it is based on Qt things should be ok, however testing is really needed.

Nicolas Bouquet

### CODE REVIEW

**Comment by SinisterSoft** [comment]
This is amazing - hopefully Arturs can add it to the main build asap and the 'kickstarter team'can add the extra functionality to their versions. :)

**Comment by john-blackburn** [comment]
Hello 

Wow this looks very impressive, great work. However I wonder if you could put a compile time switch to allow optional use of ES 1.1 ? My direct x stuff is based on OpenGL 1.1 so a one way switch to es 2.0 is going to break it.

John

-----Original Message-----

**Comment by hgy29** [comment]
John, I've just added the compile time switch you need. By defining GIDEROS_GL1 preprocessor token, shader stuff is removed and calls are made assuming GL1 API.
Beside this, I was just figuring out that Sprite hitTest would only work in 3D for surfaces located at Z=0.This could be enhanced later.

**Comment by ar2rsawseen** [comment]
So @john-blackburn and @atilimcetin , safe to merge?

**Comment by hgy29** [comment]
@ar2rsawseen, don't merge yet, I've just discovered a bug that my build script had hidden to me. I'm working on the correction right now.

**Comment by hgy29** [comment]
Ok now everything is working as expected on Windows, Android and iOS.
I've added a clipping function. Spriter:setClip(x,y,w,h) now clips the output rendering to a particular region, and children are clipped also. Will be convenient to build a pure lua widgetkit with gideros.

**Comment by SinisterSoft** [comment]
setClip will be very useful.

**Comment by ar2rsawseen** [comment]
is setClip OpenGLES 2 only?
I wanted to try to make the first version with OpenGL ES 1

**Comment by hgy29** [comment]
setClip relies on glScissor only, and It looks like It is a available on OpenGL 1

**Pull request merged**
