### PR TITLE
[gideros] get/set method

### PR DESCRIPTION
**Pull request by tkhnoman**

### CODE REVIEW

**Comment by john-blackburn** [comment]
Looks awesome, tkhnoman, many thanks. So it seems pen tablet events are completely new events right? So I need to register with sprite:addEventListener(Event.PENTABLET_PRESS, func, self) ? I think it's good to make them completely separate like this. And of course iOS, Android etc will not dispatch these events. And then I see event.pointerType, tiltx, tilty, pressure

**Comment by tkhnoman** [comment]
Yes, it's a new event which kind of rare to be in game engine...

I haven't check whether it would be an error for another platform or not though (even though it won't dispatch on them). I read through the code and i think it won't be a problem. I hope you and the team could help to check that for me. Thanks. :)

**Comment by ar2rsawseen** [comment]
So you guys think that approach is better than adding pressure property to touch events?

From end developer point of view it is another event to add and track
With touch properties having pressure property it would be only using single event (all other platforms by default would use 0 value for pressure)

so no additional checks and easier to use in my opinion.

what do you guys think?

**Comment by tkhnoman** [comment]
No @ar2rsawseen, they are totally different device input.
PenTablet is tools used for drawing, which rarely used by other than artist. I guess it would be used for app (and not game). The most popular is Wacom. It also can detect tilt of the pen, but it does not support multi touch like the one that attached at touch events.

I guess it kind of weird, probably better as a plugin, so it ups to you guys whether to accept this pull request or not.
If not, i would upload again with only get/set method and mouse bug fix.

I already prepared pressure for touch at real touch device, but i don't have any touch device that detect pressure, so i asked SinisterSoft for testing.

**Comment by tkhnoman** [comment]
On second though, i will take this back, and reupload the set/get method only.
Will try to make plugin for pen tablet

**Pull request closed without merging**
