### PR TITLE
Apple TV Support

### PR DESCRIPTION
**Pull request by acalatrava**
I've added AppleTV Support by modifying the following code:

 - Added ifdef-endif on relevant places where some iOS classes are not available on AppleTV
 - Rewritten UIAlertView by using the new UIAlertController since UIAlertView is deprecated on iOS8 and it it nos available on iOS9 and appletvos SDK.
 - Modify iOS Template so it could create a AppleTV executable (now there is two targets, one for iOS and one for AppleTV)
 - Force orientation to eLandscapeRight
 - New script to build appletvos libraries & plugins
 - Creation of a new Plugin called MFIController to deal with GCController class. The new Apple Remote should be recognized as GCController device of GCMicroGamePad profile. Unfortunately this is cannot be tested since it's not available yet on the current XCode 7.1-beta seed, but it should be available soon.

### CODE REVIEW

**Comment by john-blackburn** [comment]
Wow! This is an amazing piece of work, done very quickly! I'll take a quick look through the code and then accept the pull request. It all looks good on first glance but just want to check a bit more carefully. Thanks very much for doing this!

**Comment by acalatrava** [comment]
Thanks! I think there is an error since I replaced UIAlertView with UIAlertController but this new API is only available on iOS8. I will review this and post a new pull request.

**Comment by john-blackburn** [comment]
Thanks, actually you can simply commit your new changes and they will
become part of the existing pull request. Or you can make a new one if you
prefer.

**Comment by SinisterSoft** [comment]
You will have to check which version of the OS that is running and call the appropriate alert. ?

**Comment by acalatrava** [comment]
I think I just fixed all the issues :)
 - TextInputDialog and AlertDialog implementation now should work correctly on iOS and AppleTV no matter what iOS version you are using. If the version is previous to iOS8 it will use UIAlertView, and UIAlertController otherwise.
 - I fixed a few issues on the MFIController so it will compile fine on both platforms.
 - I modified the template to use the same library names and to preserve the app name during the exportation. If you just drop the new template over the older one on your Gideros release it will work fine when you use the iOS export (so you can compile to iOS and tvOS) :)

I'm uploading a compiled template ready to use to Dropbox just in case you want to test it on your running Gideros.

**Pull request merged**
