### PR TITLE
PR with player corrections - new zoom menu - firsts funcs of desk export - and some minor issues

### PR DESCRIPTION
**Pull request by marceloLiberton**
Hi Arturs!

Im making a PR with these new features:
- Autoscale disable/enable window to fit the canvas
- New Zoom menu with 2 new funcs, double and triple size
- Some minor corrections
- Adding first steps of desk export functions, unable to use right now

I'm think that I can make this "little" PRs to make easy to you incorporate in gideros :)

Soon, I will make another PR, with more code of desk functions and other things.

Tks.

### CODE REVIEW

**Comment by ar2rsawseen** [comment]
Awesome, will check it out this evening ;)

**Comment by marceloLiberton** [comment]
:D Nice, I think that today I will make another PR with application:setWindowSize(bool) and application:setFullScreen(int width, int height) new functions.

I guess that it can be auto merged. :)

**Comment by ar2rsawseen** [comment]
Ok then I can wait for it, but I think it should be bool and int, int vice versa :)

**Comment by ar2rsawseen** [comment]
So Marcelo you are all done? I can merge? :)

**Pull request merged**
