### PR TITLE
Master

### PR DESCRIPTION
**Pull request by alexzheng**
Fix orientation issue, and remove deprecated apis

### CODE REVIEW

**Comment by hgy29** [comment]
Hi @alexzheng, can you somehow ensure that the PR only contains needed modifications ? I see there are a lot of files deleted, which is obviously wrong...

I can manually pick up and merge the right files, but it takes some time, it is error prone, and you won't get the credit for the patch you did...

**Comment by alexzheng** [comment]
In the last pull request,I added some script files  and deleted some jar files by mistake. I have removed the scripts,I wonder if the jar files are stills needed in the github,If it is,I can add it again.

**Comment by alexzheng** [comment]
All the jar files have already add back again.
But I have never delete these file manually.

**Comment by hgy29** [comment]
Thanks. Can you add back the libImmEndpoint.so file in plugins/ads/xxx too ?
Don't know what it is used for, but better not remove it for now.
This is one gets deleted by ndk-build each time the ads plugin is built, I have too manually check it out back after each build (or before each commit to gideros)

**Comment by alexzheng** [comment]
In the last add jar files commit, I have already  recover the libs folder, and committed all the changed files. I do not  know why the plugins/ads/source/Android/libs/armeabi/libImmEndpointWarpJ.so is not in the changed files list. that file is in my local folder, but can not be committed.
Could you please bother to accept all my commits in this pull request first and add the libImmEndpointWarpJ.so in the master branch manually later.  Only in this way, I will get a clear pull request next time. 
Sorry for this inconvenience by my careless.

**Comment by alexzheng** [comment]
It seems  I can not  commit .so files,
libImmEndpointWarpJ.so copy can commit, but any file with a  suffix .so can not be committed.

**Comment by hgy29** [comment]
you can override it by git add -f

**Comment by alexzheng** [comment]
Thanks for your help.

**Pull request merged**
