### PR TITLE
[gideros] touch pressure & type

### PR DESCRIPTION
**Pull request by tkhnoman**
Haven't check with the new version yet.

### CODE REVIEW

**Comment by ar2rsawseen** [comment]
Hello, all seems great and it seems you already added support for QT, right?

Question, what is the purpose of

    touch->pressure * 0.0001

and multyiplying pressure by 10000 in QT?

**Comment by tkhnoman** [comment]
Since pressure value is float (between 0 to 1.0) and i don't want to bother with float between function, i convert them to integer.

Much pressure only reach not up to 4096 pressure sensitivity, so i guess 10000 is fine enogh.

**Comment by tkhnoman** [comment]
If possible, please change it to float later, because i'm not used to it.

**Comment by ar2rsawseen** [comment]
Ok thanks, will do ;)

**Comment by hgy29** [comment]
libgid doesn't compile anymore :( didn't you forget to push modified ginput.h with new pressure related fields ?

**Comment by tkhnoman** [comment]
Seems like i forgot one file to pull request. Sorry. Will add

**Pull request merged**
