### PR TITLE
Add  scale mode options for splash image

### PR DESCRIPTION
**Pull request by alexzheng**
Currently, option show all will keep all the contents of the original
image and may fill the margin with background color
Option Crop will fill the whole screen and some contents may be cropped.
Both options preserving the aspect ratio.

### CODE REVIEW

**Comment by alexzheng** [comment]
Will it be available in the incoming 2012.12.1 release？

**Comment by alexzheng** [comment]
I want to commit another feature to the master, With this opened, it seems I can not make a new pull request.

**Comment by hgy29** [comment]
@john-blackburn started build yesterday evening, so merges are freezed until he finish, and no it won't be in 2016.12.1

**Comment by alexzheng** [comment]
That's ok,I get it.

**Pull request merged**
